name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Load apps.json to environment
        run: echo "APPS_JSON_BASE64=$(base64 --wrap=0 ./apps.json)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Containerfile
          push: true
          build-args: |
            APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-14

          tags: |
            ahuahuachi/frappe_helpdesk:latest
